improved qqemu

diff --git a/bin/qqemu b/bin/qqemu
--- a/bin/qqemu
+++ b/bin/qqemu
@@ -5,23 +5,31 @@
 # test boot in a qemu instance (disks snapshotted, no network)
 # ~pbeck 2020
 
-if [ "$1" == "" ]; then
-	echo "Usage: qqemu DISK"
-	echo "  - Starts qemu with a copy-on-write snapshotted version of DISK."
-	echo "  - Provides VNC screen access on port 127.0.0.1:5907"
-	echo "  - Machine starts suspended until you type 'c' to boot"
-	echo "  - Use to debug Bootloader problems"
+set -eu
+
+if [ "${1:-""}" == "" ]; then
+	echo "Usage: qqemu DISK [DISK...]"
+	echo " - Starts qemu with a copy-on-write snapshotted version of DISK"
+	echo "   (or multiple of them, mind you more than 4 require virtio-blk-pci, see below)"
+	echo " - Provides VNC screen access on port 127.0.0.1:5907"
+	echo "   (or GTK interface if DISPLAY is set)"
+	echo " - Machine starts suspended until you type 'c' to continue boot"
+	echo " - Useful to debug Bootloader problems"
+	echo " - 'commit drive-diskX' will persist changes to the named disk, 'all' for all"
 	echo
 	echo "Environment variables and their defaults:"
-	echo "  KEYBOARD='de'"
-	echo "  MEMORY='1024'"
-	echo "  ENABLE_KVM='no'"
-	echo "  VNC_DISPLAY='127.0.0.1:7' (note how display 7 = port 5907)"
-	echo "  DISK2='' (secondary disk, e.g. for raid)"
-	echo "  DRIVE_TYPE='ide-hd' (change to 'virtio-blk-pci' if supported by guest)"
+	echo " KEYBOARD=de"
+	echo " MEMORY=1024"
+	echo " ENABLE_KVM=no"
+	echo " NET=no                    # 'yes' enables NAT network, MAC address cloned from host to virtual e1000"
+	echo " BIOS=legacy               # change to 'uefi' when required"
+	echo " VNC_DISPLAY=127.0.0.1:7   # (note how display 7 = port 5907)"
+	echo " DRIVE_TYPE=ide-hd         # (change to 'virtio-blk-pci' if supported by guest)"
+	echo " CDROM=''                  # name a file to boot as CD-ROM in IDE drive 4 of 4"
+	echo " QQEMU_CUSTOM=''           # custom arguments to pass to qemu"
 	echo ""
-	echo "Prepend environment variables to launch with custom values:"
-	echo "  MEMORY=4096 ENABLE_KVM=yes qqemu DISK"
+	echo "Prepend environment variables like this to launch with custom values:"
+	echo " MEMORY=4096 ENABLE_KVM=yes qqemu DISK"
 	echo
 	exit 0
 fi
@@ -30,9 +38,10 @@ memory=${MEMORY:-1024}
 vnc_display=${VNC_DISPLAY:-"127.0.0.1:7"}
 drive_type=${DRIVE_TYPE:-"ide-hd"} # virtio-blk-pci
 keyboard=${KEYBOARD:-"-k de"}
+bios=${BIOS:-"legacy"}
 
 # TODO: detect KVM availability
-if [ "$ENABLE_KVM" == "yes" ]; then
+if [ "${ENABLE_KVM:-""}" = "yes" ]; then
 	enable_kvm="-enable-kvm"
 	accel_kvm=",accel=kvm"
 else
@@ -40,50 +49,88 @@ else
 	accel_kvm=""
 fi
 
-# check primary disk exists
-vdisk="$1"
-if [ ! -e "$vdisk" ]; then
-	vdisk="/dev/$vdisk"
-fi
-if [ ! -e "$vdisk" ]; then
-	echo "Disk does not exist"
-	exit 1
-fi
-if [ "$drive_type" == "ide-hd" ]; then
-	vdisk_cmd="\
-		-drive file=${vdisk},format=raw,if=none,id=drive-disk0,snapshot=on \
-		-device ide-hd,bus=ide.0,unit=0,drive=drive-disk0,id=ide0-0-0,bootindex=1 \
-	"
+if [ "$bios" = "legacy" ]
+then
+	bios_cmd=""
 else
-	vdisk_cmd="\
-		-drive file=${vdisk},format=raw,if=none,id=drive-disk0,snapshot=on \
-		-device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x7,drive=drive-disk0,id=virtio-disk0,bootindex=1 \
-	"
+	bios_cmd=" -bios /usr/share/ovmf/OVMF.fd"
 fi
 
-# add secondary disk
-vdisk2="${DISK2}"
-vdisk_cmd2=""
-if [ "$DISK2" != "" ]; then
-	if [ ! -e "$vdisk2" ]; then
-		vdisk2="/dev/$vdisk2"
+vdisk_cmd=""
+vdisk_idx0=0
+vdisk_idx1=1
+for vdisk in "$@"
+do
+	if [ ! -e "$vdisk" ]
+	then
+		vdisk="/dev/$vdisk"
 	fi
-	if [ ! -e "$vdisk2" ]; then
-		echo "Disk 2 does not exist"
-		exit 2
+	if [ ! -e "$vdisk" ]
+	then
+		echo "Disk does not exist: $vdisk"
+		exit 1
 	fi
-	
-	if [ "$drive_type" == "ide-hd" ]; then
-		vdisk_cmd2="\
-			-drive file=${vdisk2},format=raw,if=none,id=drive-disk1,snapshot=on \
-			-device ide-hd,bus=ide.0,unit=1,drive=drive-disk1,id=ide0-0-1,bootindex=2 \
+	if [ "$drive_type" = "ide-hd" ]
+	then
+		ide_bus=$((vdisk_idx0/2))
+		ide_drive=$((vdisk_idx0%2))
+		vdisk_cmd="$vdisk_cmd \
+			-drive file=${vdisk},format=raw,if=none,id=drive-disk${vdisk_idx0},snapshot=on \
+			-device ide-hd,bus=ide.${ide_bus},unit=${ide_drive},drive=drive-disk${vdisk_idx0},id=ide${ide_bus}-0-${ide_drive},bootindex=${vdisk_idx1} \
 		"
 	else
-		vdisk_cmd2="\
-			-drive file=${vdisk2},format=raw,if=none,id=drive-disk1,snapshot=on \
-			-device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x7,drive=drive-disk1,id=virtio-disk1,bootindex=2 \
+		pci_dev=$((vdisk_idx0 + 9))
+		vdisk_cmd="$vdisk_cmd \
+			-drive file=${vdisk},format=raw,if=none,id=drive-disk${vdisk_idx0},snapshot=on \
+			-device virtio-blk-pci,scsi=off,bus=pci.0,addr=${pci_dev},drive=drive-disk${vdisk_idx0},id=virtio-disk${vdisk_idx0},bootindex=${vdisk_idx1} \
 		"
 	fi
+	((vdisk_idx0++)) || true
+	((vdisk_idx1++)) || true
+done
+
+if [ "${DISPLAY:-""}" != "" ]
+then
+	display_cmd2="-display gtk,show-tabs=on,window-close=off"
+else
+	display_cmd2=""
+fi
+
+if [ "${CDROM:-""}" != "" ]
+then
+	if [ ! -e "$CDROM" ]
+	then
+		CDROM="/dev/$CDROM"
+	fi
+	if [ ! -e "$CDROM" ]
+	then
+		echo "CDROM does not exist: $CDROM"
+		exit 1
+	fi
+	cdrom="\
+	-drive file=${CDROM},format=raw,if=none,id=drive-cdrom,media=cdrom,snapshot=on \
+	-device ide-cd,bus=ide.1,unit=1,drive=drive-cdrom,id=ide1-1-1,bootindex=0 \
+	-boot d \
+	"
+else
+	cdrom=""
+fi
+
+if [ "${NET:-"no"}" = "yes" ]
+then
+	# clone first mac address of the host
+	macaddr=",macaddr=$(ip link | awk '/ether/ {print $2; exit}')" || macaddr=""
+	net_cmd="-net user -net nic,addr=0x3,model=e1000${macaddr}"
+else
+	net_cmd=""
+fi
+
+if [ "${QQEMU_CUSTOM:-""}" != "" ]
+then
+	# clone first mac address of the host
+	custom_cmd="$QQEMU_CUSTOM"
+else
+	custom_cmd=""
 fi
 
 # for modifications to be visible to the started guest on subsequent reboots,
@@ -101,7 +148,8 @@ qemu-system-x86_64 \
 	-machine pc-i440fx-2.1${accel_kvm},usb=off \
 	-cpu qemu64 \
 	-m ${memory} \
-	-realtime mlock=off \
+	${bios_cmd} \
+	-overcommit mem-lock=off \
 	-no-user-config \
 	-nodefaults \
 	-monitor stdio \
@@ -112,17 +160,22 @@ qemu-system-x86_64 \
 	-global PIIX4_PM.disable_s3=1 \
 	-global PIIX4_PM.disable_s4=1 \
 	-boot menu=on,strict=on \
+	${cdrom} \
 	${vdisk_cmd} \
-	${vdisk_cmd2} \
 	-device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x5.0x7 \
 	-device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x5 \
 	-device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x5.0x1 \
 	-device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x5.0x2 \
 	-device usb-tablet,id=input0 \
-	-vnc ${vnc_display} \
+	-vnc ${vnc_display},non-adaptive=on \
+	${display_cmd2} \
 	${keyboard} \
 	-device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,bus=pci.0,addr=0x2 \
 	-device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x8 \
-	-msg timestamp=on
+	${net_cmd} \
+	${custom_cmd} \
+	-msg timestamp=on \
+	;
+
 exit
 }
