devtools update to support Debian from Jessie to Trixie test drives

diff --git a/devel/docker/Dockerfile-Debian b/devel/docker/Dockerfile-Debian
--- a/devel/docker/Dockerfile-Debian
+++ b/devel/docker/Dockerfile-Debian
@@ -7,10 +7,17 @@ ARG BUILD_FROM
 ENV LC_ALL C.UTF-8
 ENV DEBIAN_FRONTEND noninteractive
 
-RUN apt-get update && apt-get install -y \
+
+RUN apt-get update || \
+	# if apt-get update fails, try switching *.debian.org for archive.debian.org and remove "-updates" lines
+	(sed --in-place=.bak 's/security.debian.org/archive.debian.org/g;s/deb.debian.org/archive.debian.org/g;/-updates/d' /etc/apt/sources.list && apt-get update) || \
+	# as last resport, try again with the very slow snapshot archives
+	(sed --regex '/snapshot/!s/^/#/g;/snapshot/s/^# ?//g' /etc/apt/sources.list.bak > /etc/apt/sources.list && apt-get update)
+RUN apt-get install -y \
 	lsb-release gettext-base man-db xz-utils \
-	htop tmux procps mc screen curl \
-	less sudo vim
+	htop tmux procps mc screen curl ssh openssh-server netcat.openbsd aptitude \
+	less sudo vim pv
+RUN apt-get install -y iproute2 || echo "No iproute2 available, ss and consequently 'lsports' will not work"
 
 RUN apt-get install -y gpg || echo
 RUN apt-get install -y libncurses6 || echo
@@ -24,7 +31,7 @@ RUN apt-get install -y software-properties-common || echo
 #RUN rm -rf /var/lib/apt/lists/*
 
 COPY added/fish-installer.sh /fish-installer.sh
-RUN /fish-installer.sh
+RUN /fish-installer.sh || (less -R "/root/fish_installer.log" && exit 1)
 
 # nerdlevel 3 by default
 ENV LC_NERDLEVEL 3
